apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: httpd
        image: httpd:alpine3.19
        command: ["/bin/sh", "-c"]   # use /bin/sh since Alpine doesn't have bash
        args: ["sleep 5; exit 1"]    # sleep 5 seconds, then exit with an error
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3

